#!/bin/bash
set +x

cd "${BASH_SOURCE%/*}" || exit 
PWD=`pwd -P`
echo $PWD

cd "$PWD"
#/usr/bin/mono BingDownloader.exe
java -jar BingDownloader-1.0.jar
# Find if gdrive exists, then upload the new images
which gdrive && find . -name "*.jpg" -mtime -1 -exec gdrive upload {} \;
